CC = gcc
SRC = ./src
INC = ./include
OBJ = ./obj
BIN = ./bin

CFLAGS = -Wall -g -o
IFLAGS = -I $(INC)
LDFLAGS = -c


calc: $(OBJ)/cal.o $(OBJ)/cal_fun.o
	$(CC) $(CFLAGS) $(BIN)/calc $(OBJ)/cal.o $(OBJ)/cal_fun.o	
$(OBJ)/cal.o: $(SRC)/cal.c
	$(CC) $(LDFLAGS) $(IFLAGS) $(SRC)/cal.c
$(OBJ)/cal_fun.o: $(SRC)/cal_fun.c
	$(CC) $(LDFLAGS) $(IFLAGS) $(SRC)/cal_fun.c
	mv *.o $(OBJ)
clean: 
	rm $(OBJ)/*.o
	rm $(BIN)/*
	

